old_sound_rabbit_mq:
    connections:
        default:
            host:     127.0.0.1
            port:     5672
            user:     guest
            password: guest
            vhost:    /
            lazy:     true
    producers:
        order_create:
            connection:       default
            exchange_options: { name: order_create_ex, type: topic }
    consumers:
        order_create_bmw:  
            connection:       default
            exchange_options: { name: order_create_ex, type: topic }
            queue_options:
                name: order_create_bmw_qu
                routing_keys:
                    - 'bmw.#'
            callback:         consumer.order_create_bmw
        order_create_audi_mercedes:
            connection:       default
            exchange_options: { name: order_create_ex, type: topic }
            queue_options:
                name: order_create_audi_mercedes_qu
                routing_keys:
                    - 'audi.*'
                    - '#.mercedes.*'
            callback:         consumer.order_create_audi_mercedes