<?php

namespace ContainerNxHyxH2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldSoundRabbitMq_PartsHolderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'old_sound_rabbit_mq.parts_holder' shared service.
     *
     * @return \OldSound\RabbitMqBundle\RabbitMq\AmqpPartsHolder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-amqplib'.\DIRECTORY_SEPARATOR.'rabbitmq-bundle'.\DIRECTORY_SEPARATOR.'RabbitMq'.\DIRECTORY_SEPARATOR.'AmqpPartsHolder.php';

        return $container->services['old_sound_rabbit_mq.parts_holder'] = new \OldSound\RabbitMqBundle\RabbitMq\AmqpPartsHolder();
    }
}
