<?php

namespace ContainerMCvFz3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEventListener_OrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'event_listener.order' shared autowired service.
     *
     * @return \App\EventListener\OrderListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-amqplib'.\DIRECTORY_SEPARATOR.'rabbitmq-bundle'.\DIRECTORY_SEPARATOR.'RabbitMq'.\DIRECTORY_SEPARATOR.'BaseAmqp.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-amqplib'.\DIRECTORY_SEPARATOR.'rabbitmq-bundle'.\DIRECTORY_SEPARATOR.'RabbitMq'.\DIRECTORY_SEPARATOR.'ProducerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-amqplib'.\DIRECTORY_SEPARATOR.'rabbitmq-bundle'.\DIRECTORY_SEPARATOR.'RabbitMq'.\DIRECTORY_SEPARATOR.'Producer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Producer'.\DIRECTORY_SEPARATOR.'OrderCreateProducer.php';

        return $container->privates['event_listener.order'] = new \App\EventListener\OrderListener([0 => new \App\Producer\OrderCreateProducer([0 => ($container->services['old_sound_rabbit_mq.order_create_producer'] ?? $container->load('getOldSoundRabbitMq_OrderCreateProducerService'))])]);
    }
}
