<?php

namespace ContainerMCvFz3j;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOldSoundRabbitMq_OrderCreateProducerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'old_sound_rabbit_mq.order_create_producer' shared service.
     *
     * @return \OldSound\RabbitMqBundle\RabbitMq\Producer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-amqplib'.\DIRECTORY_SEPARATOR.'rabbitmq-bundle'.\DIRECTORY_SEPARATOR.'RabbitMq'.\DIRECTORY_SEPARATOR.'BaseAmqp.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-amqplib'.\DIRECTORY_SEPARATOR.'rabbitmq-bundle'.\DIRECTORY_SEPARATOR.'RabbitMq'.\DIRECTORY_SEPARATOR.'ProducerInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'php-amqplib'.\DIRECTORY_SEPARATOR.'rabbitmq-bundle'.\DIRECTORY_SEPARATOR.'RabbitMq'.\DIRECTORY_SEPARATOR.'Producer.php';

        $container->services['old_sound_rabbit_mq.order_create_producer'] = $instance = new \OldSound\RabbitMqBundle\RabbitMq\Producer(($container->services['old_sound_rabbit_mq.connection.default'] ?? $container->load('getOldSoundRabbitMq_Connection_DefaultService')));

        $instance->setExchangeOptions(['name' => 'order_create_ex', 'type' => 'topic', 'passive' => false, 'durable' => true, 'auto_delete' => false, 'internal' => false, 'nowait' => false, 'declare' => true, 'arguments' => NULL, 'ticket' => NULL]);
        $instance->setQueueOptions(['name' => '', 'declare' => false]);
        $instance->setDefaultRoutingKey('');
        $instance->setContentType('text/plain');
        $instance->setDeliveryMode(2);
        if ($container->has('event_dispatcher')) {
            $instance->setEventDispatcher(($container->services['event_dispatcher'] ?? $container->getEventDispatcherService()));
        }

        return $instance;
    }
}
