<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMCvFz3j\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMCvFz3j/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMCvFz3j.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMCvFz3j\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMCvFz3j\App_KernelDevDebugContainer([
    'container.build_hash' => 'MCvFz3j',
    'container.build_id' => 'f4a89825',
    'container.build_time' => 1641312068,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMCvFz3j');
